---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-icd-mysql
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 4be16b65-3efc-457e-bc30-690e3ac7a6a1
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
