---
apiVersion: v1
offerings:
  - name: terraform-ibm-icd-mysql
    kind: module
    catalog_id: _
    offering_id: _
    examples:
      - name: basic
        mark_ready: true
      - name: complete
        mark_ready: true
      - name: fscloud
        mark_ready: true
  - name: deploy-arch-ibm-icd-mysql
    kind: solution
    catalog_id: _
    offering_id: _
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south